### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pronguen** [rero/reroils-data#7]
In the institution form, the code of the library and of the location should be translated in
- FR: Code (currently: Code-barres)
- IT: Codice (currently: Codice a barre)
- DE: Code (currently: Strichcode)

In the institution form, the part named "collocazione" should be named "Collocazioni". In DE/FR/EN, the translation is ok.

In the bottom of the institution form, it is not understandable why the phrases "Locations of the library." and "Libraries of the institution." are displayed. They should be removed.

**Comment by iGormilhit** [comment]
This is solved through the rewriting of Organisations/members/locations and the translations process for the sprint 5 deployement.
